# Generated by Django 5.1.4 on 2024-12-20 10:08

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=64, unique=True)),
                ('secret', models.TextField()),
                ('passphrase', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 12, 21, 10, 8, 0, 282390, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
