# Generated by Django 5.1.4 on 2024-12-22 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 21, 21, 24, 663143, tzinfo=datetime.timezone.utc)),
        ),
    ]
